In [1]:
# to check terminal states
def terminal_state(state):
    x, y = state
    return (x == 0 and y == 0) or (x == 3 and y == 3)


In [2]:
# Function for taking Setps in Grid world problem
def Step(state, action):
    state = np.array(state)
    new_state = (state + action).tolist()
    x, y = new_state

    if x < 0 or x >= gridsize or y < 0 or y >= gridsize:
        new_state = state.tolist()

    reward = -1
    return new_state, reward

In [3]:
# Function for computing optimal Policy
def OptimalPolicy(state, action , v): 
    state = np.array(state)
    new_state = (state+action).tolist()
    x, y = new_state
    if x < 0 or x >= gridsize or y < 0 or y >= gridsize:
        x,y = state
        value = v[x,y]
        new_state = state
    else:
        value = v[x,y]
    return  value

In [4]:
# 0 - Left , 1 - UP , 2 - RIGHT , 3 - Down  
def VI():     #value Iteration
    new_state_values = np.zeros((gridsize, gridsize))
    state_values = np.zeros((gridsize, gridsize))
    it = 0
    it = it+1
    while True:
       
        for i in range(gridsize):
            for j in range(gridsize):
                temp = []
                if terminal_state([i, j]):
                    continue
                value = 0
                
                for action in actions:
                    (p,q ), reward = Step([i, j], action)
                    value += prob * (reward + state_values[p, q]) # computing value function
                new_state_values[i, j] = value
                
        if np.sum(np.abs(new_state_values - state_values)) < theta: # Termination Condition
            state_values = new_state_values.copy()
            break

        state_values = new_state_values.copy()
        print('Iteration - ',it)
        print(state_values)
        
        for i in range(0,gridsize):
            for j in range(0,gridsize):
                temp = []
                for a in actions:
                    if terminal_state([i,j]):
                        value1 = 0.0
                    value1 = OptimalPolicy([i,j],a,state_values)
                    temp.append(value1)
     
                z = [p for p, t in enumerate(temp) if t == max(temp)]
       
                print("Optimal Policy for State:",(i,j),"---",z)
            it += 1

   
    return state_values



In [5]:
# policy Improvement
def policyImprovement(old_policy,values):
    s = 0
    new_policy = np.zeros((gridsize*gridsize,len(index)))
    for i in range(gridsize):
        for j in range(gridsize):
            if terminal_state([i, j]):
                continue
            q_optimal = values[i,j]
            z = []
            for ix,a in zip(index,actions):
                #P  = old_policy[n,inx]
                (p,q), reward = Step([i, j], a)
                q_sa = (reward + values[p,q]) # action value function computation
                if q_sa > q_optimal: # update policy condition
                    z.append(ix)
           
            if len(z)>0:
                for k, l in enumerate(z):
                    #y = np.array(k)
                    new_policy[s,l] = 1/len(z)
            else:
                new_policy[s,:] = old_policy[s,:]
            s = s+1        
    return new_policy

In [6]:
import numpy as np
gridsize = 4
terminal_state1 = [0,0]
terminal_state2 = [3,3]
actions=[[0,-1],[-1,0],[0,1],[1,0]]
prob = 0.25
theta = 1e-4
values = VI() # run value iteration function


Iteration -  1
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0, 1, 2, 3]
Optimal Policy for State: (0, 3) --- [0, 1, 2, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0, 1, 2, 3]
Optimal Policy for State: (1, 2) --- [0, 1, 2, 3]
Optimal Policy for State: (1, 3) --- [0, 1, 2, 3]
Optimal Policy for State: (2, 0) --- [0, 1, 2, 3]
Optimal Policy for State: (2, 1) --- [0, 1, 2, 3]
Optimal Policy for State: (2, 2) --- [0, 1, 2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [0, 1, 2, 3]
Optimal Policy for State: (3, 1) --- [0, 1, 2, 3]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  5
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
Optimal Policy for State: (0, 0)

Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  81
[[  0.          -9.6914631  -13.61551807 -14.85540061]
 [ -9.6914631  -12.37563554 -13.65823835 -13.61551807]
 [-13.61551807 -13.65823835 -12.37563554  -9.6914631 ]
 [-14.85540061 -13.61551807  -9.6914631    0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0, 1]
Optimal Policy for State: (1, 2) --- [0, 3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1, 2]
Optimal Policy for State: (2, 2) --- [2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2

Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0, 1]
Optimal Policy for State: (1, 2) --- [0, 3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1, 2]
Optimal Policy for State: (2, 2) --- [2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  121
[[  0.         -11.505805   -16.30405188 -17.8640157 ]
 [-11.505805   -14.74408805 -16.3287757  -16.30405188]
 [-16.30405188 -16.3287757  -14.74408805 -11.505805  ]
 [-17.8640157  -16.30405188 -11.505805     0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 

Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0]
Optimal Policy for State: (1, 2) --- [0, 3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1, 2]
Optimal Policy for State: (2, 2) --- [2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  241
[[  0.         -13.51612663 -19.2829868  -21.19761983]
 [-13.51612663 -17.36835377 -19.28778314 -19.2829868 ]
 [-19.2829868  -19.28778314 -17.36835377 -13.51612663]
 [-21.19761983 -19.2829868  -13.51612663   0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]


Optimal Policy for State: (1, 2) --- [0]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1]
Optimal Policy for State: (2, 2) --- [2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  329
[[  0.         -13.8546374  -19.78459881 -21.75895333]
 [-13.8546374  -17.81024429 -19.7860397  -19.78459881]
 [-19.78459881 -19.7860397  -17.81024429 -13.8546374 ]
 [-21.75895333 -19.78459881 -13.8546374    0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0, 1]
Optimal Policy for State: (1, 2) --- [3]
Optimal Policy for State: (1, 3) --- [3]
Optima

Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  477
[[  0.         -13.98076579 -19.97149837 -21.96810499]
 [-13.98076579 -17.97489175 -19.97168903 -19.97149837]
 [-19.97149837 -19.97168903 -17.97489175 -13.98076579]
 [-21.96810499 -19.97149837 -13.98076579   0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0, 1]
Optimal Policy for State: (1, 2) --- [0, 3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1, 2]
Optimal Policy for State: (2, 2) --- [2]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]


Optimal Policy for State: (2, 2) --- [3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  537
[[  0.         -13.99152822 -19.98744634 -21.98595171]
 [-13.99152822 -17.98894097 -19.98753032 -19.98744634]
 [-19.98744634 -19.98753032 -17.98894097 -13.99152822]
 [-21.98595171 -19.98744634 -13.99152822   0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0]
Optimal Policy for State: (1, 2) --- [0, 3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1, 2]
Optimal Policy for State: (2, 2) --- [2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal P

Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0, 1]
Optimal Policy for State: (1, 2) --- [0, 3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1, 2]
Optimal Policy for State: (2, 2) --- [2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  629
[[  0.         -13.99759034 -19.99642932 -21.99600419]
 [-13.99759034 -17.99685444 -19.9964532  -19.99642932]
 [-19.99642932 -19.9964532  -17.99685444 -13.99759034]
 [-21.99600419 -19.99642932 -13.99759034   0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [

Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [0, 3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [1]
Optimal Policy for State: (1, 2) --- [0, 3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [1, 2]
Optimal Policy for State: (2, 2) --- [2]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  733
[[  0.         -13.99941828 -19.99913799 -21.99903536]
 [-13.99941828 -17.99924062 -19.99914376 -19.99913799]
 [-19.99913799 -19.99914376 -17.99924062 -13.99941828]
 [-21.99903536 -19.99913799 -13.99941828   0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Opt

Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optimal Policy for State: (3, 2) --- [2]
Optimal Policy for State: (3, 3) --- [2, 3]
Iteration -  805
[[  0.         -13.99978253 -19.99967775 -21.99963938]
 [-13.99978253 -17.99971612 -19.99967991 -19.99967775]
 [-19.99967775 -19.99967991 -17.99971612 -13.99978253]
 [-21.99963938 -19.99967775 -13.99978253   0.        ]]
Optimal Policy for State: (0, 0) --- [0, 1]
Optimal Policy for State: (0, 1) --- [0]
Optimal Policy for State: (0, 2) --- [0]
Optimal Policy for State: (0, 3) --- [3]
Optimal Policy for State: (1, 0) --- [1]
Optimal Policy for State: (1, 1) --- [0, 1]
Optimal Policy for State: (1, 2) --- [3]
Optimal Policy for State: (1, 3) --- [3]
Optimal Policy for State: (2, 0) --- [1]
Optimal Policy for State: (2, 1) --- [2]
Optimal Policy for State: (2, 2) --- [2, 3]
Optimal Policy for State: (2, 3) --- [3]
Optimal Policy for State: (3, 0) --- [1, 2]
Optimal Policy for State: (3, 1) --- [2]
Optima

In [7]:
index = np.array([0,1,2,3]) 
def valueIteration(state_values,policy):
    n=0
    for i in range(gridsize):
        for j in range(gridsize):
            if terminal_state([i, j]):
                continue
            value = 0
            for ix,a in zip(index,actions):
                P = policy[n,ix]
                (p,q), reward = Step([i, j], a)
                value +=  P*(reward + state_values[p, q]) # Value function computation 
            new_state_values[i, j] = value
    return new_state_values

In [8]:
#policy improvement

itr = 1
maxiter = 3

new_state_values = np.zeros((gridsize, gridsize))
state_values = new_state_values.copy()
old_policy = 0.25*np.ones((gridsize*gridsize,len(index))) # Random Policy
while True:
    new_state_values = valueIteration(state_values,old_policy) # run value iteration for each state, Policy Evaluation
    new_policy = policyImprovement(old_policy,new_state_values) # Policy Improvement
    # 0 -->> Left , 1 -->> UP , 2 -->> RIGHT , 3 -->> Down  
    print("New State Values")
    print(new_state_values)
  
    print("Updated Policy with policy improvement")
    print(new_policy)
    if np.sum(np.abs(new_state_values - state_values)) < theta or itr > maxiter: # Termination Condition
        state_values = new_state_values.copy()
        break
    state_values = new_state_values.copy()
    old_policy = new_policy.copy()
    itr += 1

New State Values
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
Updated Policy with policy improvement
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]]
New State Values
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
Updated Policy with policy improvement
[[1.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.   1.   0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.   0.   0.   1.  ]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.   0.   1.   0.  ]
 [0.   0.  