In [1]:
def step(state, action):
    if state == A:
        return A1, 10
    if state == B:
        return B1, 5
    state = np.array(state)
    new_state = (state+action).tolist()
    x, y = new_state
    if x < 0 or x >= gridsize or y < 0 or y >= gridsize:
        reward = -1.0
        new_state = state
    else:
        reward = 0
    return new_state, reward


In [2]:
def OptimalPolicy(state, action , v):
    if state == A:
        x,y = A1
        value = v[x,y]
        return value
    if state == B:
        x,y = B1
        value = v[x,y]
        return value
    state = np.array(state)
    next_state = (state+action).tolist()
    x, y = next_state
    if x < 0 or x >= gridsize or y < 0 or y >= gridsize:
        value = 0
        next_state = state
    else:
        value = v[x,y]
    return  value


In [3]:
import numpy as np
gridsize = 5
A = [0,1]
B = [0,3]
A1 = [4,1]
B1 = [2,3]
discount = 0.9
v= np.zeros((gridsize, gridsize))
actions=[[0,-1],[-1,0],[0,1],[1,0]]
prob = 0.25 # probability of taking particular action
v= np.zeros((gridsize, gridsize))
while True:
    v1 = np.zeros(v.shape)
    for i in range(0,gridsize):
        for j in range(0,gridsize):
            temp = []
            for a in actions:
                (p,q),reward = step([i,j],a)
                temp.append(reward + discount*v[p,q])
            v1[i,j] = np.max(temp)
    if np.sum(np.abs(v - v1)) < 1e-4:
        break
    v = v1
    
print(v)

[[21.97744338 24.41938153 21.97744338 19.41938153 17.47744338]
 [19.77969904 21.97744338 19.77969904 17.8017056  16.02153504]
 [17.8017056  19.77969904 17.8017056  16.02153504 14.41938153]
 [16.02153504 17.8017056  16.02153504 14.41938153 12.97744338]
 [14.41938153 16.02153504 14.41938153 12.97744338 11.67969904]]


In [4]:
# 0 means Left , 1 means UP , 2 means RIGHT , 3 means Down  
for i in range(0,gridsize):
    for j in range(0,gridsize):
        temp = []
        for a in actions:
            value = OptimalPolicy([i,j],a,v1)
            temp.append(value)
        print((temp))
        
        z = [p for p, t in enumerate(temp) if t == max(temp)]
        
        print("Optimal Policy for State:",(i,j),"---",z)

[0, 0, 24.41938153311321, 19.7796990418217]
Optimal Policy for State: (0, 0) --- [2]
[16.021535036792454, 16.021535036792454, 16.021535036792454, 16.021535036792454]
Optimal Policy for State: (0, 1) --- [0, 1, 2, 3]
[24.41938153311321, 0, 19.41938153311321, 19.7796990418217]
Optimal Policy for State: (0, 2) --- [0]
[16.021535036792454, 16.021535036792454, 16.021535036792454, 16.021535036792454]
Optimal Policy for State: (0, 3) --- [0, 1, 2, 3]
[19.41938153311321, 0, 0, 16.021535036792454]
Optimal Policy for State: (0, 4) --- [0]
[0, 21.97744337980189, 21.97744337980189, 17.80172913763953]
Optimal Policy for State: (1, 0) --- [1, 2]
[19.7796990418217, 24.41938153311321, 19.7796990418217, 19.7796990418217]
Optimal Policy for State: (1, 1) --- [1]
[21.97744337980189, 21.97744337980189, 17.80172913763953, 17.80172913763953]
Optimal Policy for State: (1, 2) --- [0, 1]
[19.7796990418217, 19.41938153311321, 16.021535036792454, 16.021535036792454]
Optimal Policy for State: (1, 3) --- [0]
[17.8